{
 "title": "Helmet & Backend Services Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Helmet Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(helmet_request_duration_seconds_bucket[5m])) by (url, le))"
    }
   ]
  },
  {
   "title": "Backend Services Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(helmet_srv_request_duration_seconds_bucket[5m])) by (id, le))"
    }
   ]
  },
  {
   "title": "Backend Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "helmet_srv_total_http_requests" }
   ]
  },
  {
   "title": "Helmet Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "helmet_requests_total" }
   ]
  }
 ]
}